name: "Ubuntu MIP"

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (Ubuntu)
        run: sudo apt-get update && sudo apt-get install -y libopencv-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: ctest --test-dir ${{github.workspace}}/build --build-config ${{env.BUILD_TYPE}}

      # Создание пакета для Ubuntu
      - name: Create package (Ubuntu)
        run: |
          cpack --config ${{github.workspace}}/build/CPackConfig.cmake
          mv ${{github.workspace}}/*.deb ${{github.workspace}}/build/
